In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
# url링크가 담긴 엑셀파일 불러오기
url_df = pd.read_excel('./data/youtube1 .xlsx')
url_df

       name                                       link
0      꿩불고기  https://www.youtube.com/embed/rl5xaIdHjPY
1       닭갈비  https://www.youtube.com/embed/HI8DlDs1gko
2       닭꼬치  https://www.youtube.com/embed/1xrcjy6eX7M
3      더덕구이  https://www.youtube.com/embed/ir4Z2IyFIvM
4      도미구이  https://www.youtube.com/embed/Q0W5ag8ZbzU
..      ...                                        ...
833   오징어튀김  https://www.youtube.com/embed/K7KCOvEKPbg
834    채소튀김  https://www.youtube.com/embed/1uvcqAUjH8A
835    치킨너겟  https://www.youtube.com/embed/aw1YhCxSF7c
836     탕수육  https://www.youtube.com/embed/mzZNNMM2WuQ
837  후라이드치킨  https://www.youtube.com/embed/RjVAfc7reHU

[838 rows x 2 columns]

In [3]:
# 음식정보가 담긴 엑셀파일 불러오기
food_df = pd.read_excel('./data/food_info.xlsx')
food_df

,Unnamed: 0,음식명,식품군,제조사명,지역명,중량,열량(kcal),탄수화물(g),단백질(g),지방(g),당류(g),나트륨(mg),콜레스트롤(mg),포화지방산(g),트랜스지방(g)
0,0,꿩불고기,NaN,NaN,충주,500.0,368.80,39.70,33.50,8.50,16.90,1264.31,106.18,1.90,0.10
1,1,닭갈비,NaN,NaN,전국(대표),400.0,595.61,44.90,45.90,25.80,21.20,1535.83,193.40,6.00,0.20
2,2,닭갈비,NaN,NaN,춘천,300.0,558.47,23.10,45.50,31.60,8.50,1016.94,217.67,11.30,0.30
3,3,닭꼬치,NaN,NaN,전국(대표),70.0,176.72,13.35,11.56,8.57,3.15,286.91,31.44,2.32,0.04
4,4,더덕구이,NaN,NaN,전국(대표),100.0,184.00,31.10,3.10,5.20,11.60,743.37,0.12,0.80,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90603,90603,"코코아, 가루",차류,NaN,전국(대표),100.0,268.00,43.63,22.85,20.06,0.49,24.00,0.00,12.11,0.01
90604,90604,"홍삼차, 액상",차류,NaN,전국(대표),100.0,40.00,9.27,0.28,0.24,6.32,4.00,0.00,0.00,0.00
90605,90605,"홍차, 복숭아, 가루",차류,NaN,전국(대표),100.0,397.00,98.12,0.32,0.38,42.31,41.00,0.00,0.00,0.00
90606,90606,"마요네즈, 저칼로리",조미료류,NaN,전국(대표),100.0,341.00,12.35,0.89,31.97,3.56,600.00,23.72,3.96,0.22
90607,90607,"인삼, 수삼, 삶은것",기타,NaN,전국(대표),100.0,86.00,18.23,3.54,0.69,9.18,10.00,0.00,0.05,0.00

In [4]:
# 레시피 컬럼 추가 np.nan으로 빈값으로 생성
food_df['레시피'] = np.nan
food_df

,Unnamed: 0,음식명,식품군,제조사명,지역명,중량,열량(kcal),탄수화물(g),단백질(g),지방(g),당류(g),나트륨(mg),콜레스트롤(mg),포화지방산(g),트랜스지방(g),레시피
0,0,꿩불고기,NaN,NaN,충주,500.0,368.80,39.70,33.50,8.50,16.90,1264.31,106.18,1.90,0.10,NaN
1,1,닭갈비,NaN,NaN,전국(대표),400.0,595.61,44.90,45.90,25.80,21.20,1535.83,193.40,6.00,0.20,NaN
2,2,닭갈비,NaN,NaN,춘천,300.0,558.47,23.10,45.50,31.60,8.50,1016.94,217.67,11.30,0.30,NaN
3,3,닭꼬치,NaN,NaN,전국(대표),70.0,176.72,13.35,11.56,8.57,3.15,286.91,31.44,2.32,0.04,NaN
4,4,더덕구이,NaN,NaN,전국(대표),100.0,184.00,31.10,3.10,5.20,11.60,743.37,0.12,0.80,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90603,90603,"코코아, 가루",차류,NaN,전국(대표),100.0,268.00,43.63,22.85,20.06,0.49,24.00,0.00,12.11,0.01,NaN
90604,90604,"홍삼차, 액상",차류,NaN,전국(대표),100.0,40.00,9.27,0.28,0.24,6.32,4.00,0.00,0.00,0.00,NaN
90605,90605,"홍차, 복숭아, 가루",차류,NaN,전국(대표),100.0,397.00,98.12,0.32,0.38,42.31,41.00,0.00,0.00,0.00,NaN
90606,90606,"마요네즈, 저칼로리",조미료류,NaN,전국(대표),100.0,341.00,12.35,0.89,31.97,3.56,600.00,23.72,3.96,0.22,NaN
90607,90607,"인삼, 수삼, 삶은것",기타,NaN,전국(대표),100.0,86.00,18.23,3.54,0.69,9.18,10.00,0.00,0.05,0.00,NaN

In [5]:
food_df.iloc[3,1]

'닭꼬치'

In [6]:
url_df.iloc[0,0]

'꿩불고기'

In [19]:
food_df.iloc[0,2]

nan

In [22]:
import math

In [32]:
food_df['식품군']

0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ...
90603      차류
90604      차류
90605      차류
90606    조미료류
90607      기타
Name: 식품군, Length: 90608, dtype: object

In [38]:
# 두개의 데이터 프레임에서 식품군, 제조사명이 없고 음식명이 같을때 URL추가하기
for i in tqdm(range(len(food_df))):
    if pd.isna(food_df.iloc[i,2]) and pd.isna(food_df.iloc[i,3]): # 식품군, 제조사명이 없을때
        for j in range(len(url_df)):
            if food_df.iloc[i,1] == url_df.iloc[j,0]: # 음식명이 같을때
                food_df.iloc[i,-1] = url_df.iloc[j,1]
                break

100%|██████████████████████████████████████████████████████████████████████████| 90608/90608 [00:12<00:00, 7373.06it/s]

In [41]:
food_df['레시피'].count()

831

In [42]:
food_df.to_excel('./data/food_info_url_2.xlsx', index=False)