In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
food_df = pd.read_excel('./data/food_info_url_2.xlsx', index_col='Unnamed: 0')

In [3]:
food_df

,음식명,식품군,제조사명,지역명,중량,열량(kcal),탄수화물(g),단백질(g),지방(g),당류(g),나트륨(mg),콜레스트롤(mg),포화지방산(g),트랜스지방(g),레시피
Unnamed: 0,,,,,,,,,,,,,,,
0,꿩불고기,NaN,NaN,충주,500.0,368.80,39.70,33.50,8.50,16.90,1264.31,106.18,1.90,0.10,https://www.youtube.com/embed/rl5xaIdHjPY
1,닭갈비,NaN,NaN,전국(대표),400.0,595.61,44.90,45.90,25.80,21.20,1535.83,193.40,6.00,0.20,https://www.youtube.com/embed/HI8DlDs1gko
2,닭갈비,NaN,NaN,춘천,300.0,558.47,23.10,45.50,31.60,8.50,1016.94,217.67,11.30,0.30,https://www.youtube.com/embed/HI8DlDs1gko
3,닭꼬치,NaN,NaN,전국(대표),70.0,176.72,13.35,11.56,8.57,3.15,286.91,31.44,2.32,0.04,https://www.youtube.com/embed/1xrcjy6eX7M
4,더덕구이,NaN,NaN,전국(대표),100.0,184.00,31.10,3.10,5.20,11.60,743.37,0.12,0.80,0.00,https://www.youtube.com/embed/ir4Z2IyFIvM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90603,"코코아, 가루",차류,NaN,전국(대표),100.0,268.00,43.63,22.85,20.06,0.49,24.00,0.00,12.11,0.01,NaN
90604,"홍삼차, 액상",차류,NaN,전국(대표),100.0,40.00,9.27,0.28,0.24,6.32,4.00,0.00,0.00,0.00,NaN
90605,"홍차, 복숭아, 가루",차류,NaN,전국(대표),100.0,397.00,98.12,0.32,0.38,42.31,41.00,0.00,0.00,0.00,NaN
90606,"마요네즈, 저칼로리",조미료류,NaN,전국(대표),100.0,341.00,12.35,0.89,31.97,3.56,600.00,23.72,3.96,0.22,NaN
90607,"인삼, 수삼, 삶은것",기타,NaN,전국(대표),100.0,86.00,18.23,3.54,0.69,9.18,10.00,0.00,0.05,0.00,NaN

In [4]:
df = food_df.iloc[:,4:-1].fillna(0)
print(df)

               중량  열량(kcal)  탄수화물(g)  단백질(g)  지방(g)  당류(g)  나트륨(mg)  \
Unnamed: 0
0           500.0    368.80    39.70   33.50   8.50  16.90  1264.31
1           400.0    595.61    44.90   45.90  25.80  21.20  1535.83
2           300.0    558.47    23.10   45.50  31.60   8.50  1016.94
3            70.0    176.72    13.35   11.56   8.57   3.15   286.91
4           100.0    184.00    31.10    3.10   5.20  11.60   743.37
...           ...       ...      ...     ...    ...    ...      ...
90603       100.0    268.00    43.63   22.85  20.06   0.49    24.00
90604       100.0     40.00     9.27    0.28   0.24   6.32     4.00
90605       100.0    397.00    98.12    0.32   0.38  42.31    41.00
90606       100.0    341.00    12.35    0.89  31.97   3.56   600.00
90607       100.0     86.00    18.23    3.54   0.69   9.18    10.00

            콜레스트롤(mg)  포화지방산(g)  트랜스지방(g)
Unnamed: 0
0              106.18      1.90      0.10
1              193.40      6.00      0.20
2              217.67     11.30      0.30
3               31.44      2.32      0.04
4                0.12      0.80      0.00
...               ...       ...       ...
90603            0.00     12.11      0.01
90604            0.00      0.00      0.00
90605            0.00      0.00      0.00
90606           23.72      3.96      0.22
90607            0.00      0.05      0.00

[90608 rows x 10 columns]

In [5]:
df1 = food_df.iloc[:,:4]
df1

                    음식명   식품군 제조사명     지역명
Unnamed: 0
0                  꿩불고기   NaN  NaN      충주
1                   닭갈비   NaN  NaN  전국(대표)
2                   닭갈비   NaN  NaN      춘천
3                   닭꼬치   NaN  NaN  전국(대표)
4                  더덕구이   NaN  NaN  전국(대표)
...                 ...   ...  ...     ...
90603           코코아, 가루    차류  NaN  전국(대표)
90604           홍삼차, 액상    차류  NaN  전국(대표)
90605       홍차, 복숭아, 가루    차류  NaN  전국(대표)
90606        마요네즈, 저칼로리  조미료류  NaN  전국(대표)
90607       인삼, 수삼, 삶은것    기타  NaN  전국(대표)

[90608 rows x 4 columns]

In [6]:
df2 = food_df.iloc[:,-1]
df2

Unnamed: 0
0        https://www.youtube.com/embed/rl5xaIdHjPY
1        https://www.youtube.com/embed/HI8DlDs1gko
2        https://www.youtube.com/embed/HI8DlDs1gko
3        https://www.youtube.com/embed/1xrcjy6eX7M
4        https://www.youtube.com/embed/ir4Z2IyFIvM
                           ...
90603                                          NaN
90604                                          NaN
90605                                          NaN
90606                                          NaN
90607                                          NaN
Name: 레시피, Length: 90608, dtype: object

In [7]:
food_df_0 = pd.concat([df1, df2, df], axis=1)
food_df_0

,음식명,식품군,제조사명,지역명,레시피,중량,열량(kcal),탄수화물(g),단백질(g),지방(g),당류(g),나트륨(mg),콜레스트롤(mg),포화지방산(g),트랜스지방(g)
Unnamed: 0,,,,,,,,,,,,,,,
0,꿩불고기,NaN,NaN,충주,https://www.youtube.com/embed/rl5xaIdHjPY,500.0,368.80,39.70,33.50,8.50,16.90,1264.31,106.18,1.90,0.10
1,닭갈비,NaN,NaN,전국(대표),https://www.youtube.com/embed/HI8DlDs1gko,400.0,595.61,44.90,45.90,25.80,21.20,1535.83,193.40,6.00,0.20
2,닭갈비,NaN,NaN,춘천,https://www.youtube.com/embed/HI8DlDs1gko,300.0,558.47,23.10,45.50,31.60,8.50,1016.94,217.67,11.30,0.30
3,닭꼬치,NaN,NaN,전국(대표),https://www.youtube.com/embed/1xrcjy6eX7M,70.0,176.72,13.35,11.56,8.57,3.15,286.91,31.44,2.32,0.04
4,더덕구이,NaN,NaN,전국(대표),https://www.youtube.com/embed/ir4Z2IyFIvM,100.0,184.00,31.10,3.10,5.20,11.60,743.37,0.12,0.80,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90603,"코코아, 가루",차류,NaN,전국(대표),NaN,100.0,268.00,43.63,22.85,20.06,0.49,24.00,0.00,12.11,0.01
90604,"홍삼차, 액상",차류,NaN,전국(대표),NaN,100.0,40.00,9.27,0.28,0.24,6.32,4.00,0.00,0.00,0.00
90605,"홍차, 복숭아, 가루",차류,NaN,전국(대표),NaN,100.0,397.00,98.12,0.32,0.38,42.31,41.00,0.00,0.00,0.00
90606,"마요네즈, 저칼로리",조미료류,NaN,전국(대표),NaN,100.0,341.00,12.35,0.89,31.97,3.56,600.00,23.72,3.96,0.22
90607,"인삼, 수삼, 삶은것",기타,NaN,전국(대표),NaN,100.0,86.00,18.23,3.54,0.69,9.18,10.00,0.00,0.05,0.00

In [8]:
food_df_0.to_excel('./data/food_info_찐막_2.xlsx', index=False)